name: BulkPokeScan
options:
  bundleIdPrefix: com.nytemode
  deploymentTarget:
    iOS: "16.4"
  developmentLanguage: en
  createIntermediateGroups: true
  generateEmptyDirectories: false

configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "5.9"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: Q2QT3TXJE4
    ENABLE_USER_SCRIPT_SANDBOXING: NO

targets:
  BulkPokeScan:
    type: application
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - path: BulkPokeScan
        excludes:
          - "Info.plist"
          - "PrivacyInfo.xcprivacy"
    resources:
      - path: BulkPokeScan/PrivacyInfo.xcprivacy
    settings:
      base:
        INFOPLIST_FILE: BulkPokeScan/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: Q2QT3TXJE4
        ENABLE_PREVIEWS: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: NO
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.nytemode.bulkpokescan.dev
          CODE_SIGN_IDENTITY: "Apple Development"
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.nytemode.bulkpokescan
          CODE_SIGN_IDENTITY: "Apple Distribution"
